.PHONY: Debug
Debug:
	cd dual_number; make Debug;
	cd ..;
	cd stream; make Debug;
	cd ..;
	cd interval; make Debug;
	cd ..;
	cd common; make Debug;
.PHONY: Release
Release:
	cd dual_number; make Release;
	cd ..;
	cd stream; make Release;
	cd ..;
	cd interval; make Release;
	cd ..;
	cd common; make Release;
.PHONY: clean
clean:
	cd dual_number; make clean;
	cd ..;
	cd stream; make clean;
	cd ..;
	cd interval; make clean;
  cd ..;
	cd common; make clean;