compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-4.0
      - llvm-toolchain-precise
    packages:
      - clang-4.0
      - g++-6
      - gcc-6
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6" COMPILER="g++-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.0" CC="clang-4.0" COMPILER="clang++-4.0"; fi
language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./common_lib_tests
  - ./dual_number_lib_tests
  - ./interval_lib_tests
  - ./stream_lib_tests
  - ./rkf45_lib_tests
  - ./stopwatch_lib_tests
  
