compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      - clang-3.8
      - g++-6
      - gcc-6
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.7"; fi
language: cpp
script:
  - make Debug CXX="${CXX}"
  - make clean