compiler:
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
    packages:
      - g++-6
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6" COMPILER="g++-6"; fi
language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./common_lib_tests
  - ./dual_number_lib_tests
  - ./interval_lib_tests
  - ./stream_lib_tests
  - ./rkf45_lib_tests
  - ./stopwatch_lib_tests
  - ./func_util_lib_tests
