version: 2
jobs:
  gcc_7_1:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-7.1
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_7_2:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-7.2
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_1:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.1
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_2:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.2
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_3:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.3
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_4:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.4
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_1:
    docker:
      - image: enumack/buildcontainers:gcc-5.1
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_2:
    docker:
      - image: enumack/buildcontainers:gcc-5.2
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_3:
    docker:
      - image: enumack/buildcontainers:gcc-5.3
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_4:
    docker:
      - image: enumack/buildcontainers:gcc-5.4
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_5:
    docker:
      - image: enumack/buildcontainers:gcc-5.5
    steps:
      - checkout
      - run: g++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_5_0:
    docker:
      - image: enumack/buildcontainers:clang-5.0
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_4_0:
    docker:
      - image: enumack/buildcontainers:clang-4.0
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_3_9:
    docker:
      - image: enumack/buildcontainers:clang-3.9
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_3_8:
    docker:
      - image: enumack/buildcontainers:clang-3.8
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_3_7:
    docker:
      - image: enumack/buildcontainers:clang-3.7
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_3_6:
    docker:
      - image: enumack/buildcontainers:clang-3.6
    steps:
      - checkout
      - run: clang++ -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  # clang_3_5:
  #   docker:
  #     - image: enumack/buildcontainers:clang-3.5
  #   steps:
  #     - checkout
  #     - run: clang++ -dumpversion
  #     - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util|rkf45)).*$" >> ./CMakeLists.txt
  #     - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_5_1
      - gcc_5_2
      - gcc_5_3
      - gcc_5_4
      - gcc_5_5
      - gcc_6_1
      - gcc_6_2
      - gcc_6_3
      - gcc_6_4 
      - gcc_7_1
      - gcc_7_2
      # - clang_3_5 out of support
      - clang_3_6
      - clang_3_7
      - clang_3_8
      - clang_3_9
      - clang_4_0
      - clang_5_0