version: 2
jobs:
  gcc_6:
    working_directory: /Cranberries
    docker:
      - image: enumack/docker_gcc
    steps:
      - checkout
      - run: exoprt CXX="g++-6" CC="gcc-6" COMPILER="g++-6"
      - run: cmake -DCMAKE_CXX_COMPILER=$COMPILER && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_4_0:
    working_directory: /Cranberries
    docker:
      - image: enumack/docker_clang
    steps:
      - checkout
      - run: exoprt CXX="clang++-4.0" CC="clang-4.0" COMPILER="clang++-4.0"
      - run: cmake -DCMAKE_CXX_COMPILER=$COMPILER && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_6
      - clang_4_0  