version: 2
jobs:
  gcc_6:
    working_directory: /Cranberries
    docker:
      - image: enumhack/docker_gcc
    steps:
      - checkout
      - run: cmake -DCMAKE_CXX_COMPILER=gcc-6 && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_4_0:
    working_directory: /Cranberries
    docker:
      - image: enumack/docker_clang
    steps:
      - checkout
      - run: cmake -DCMAKE_CXX_COMPILER=clang++-4.0 && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_6
      - clang_4_0  