version: 2
jobs:
  gcc_7:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-7
    steps:
      - checkout
      - run: echo "add_subdirectory(test)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  gcc_6:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6
    steps:
      - checkout
      - run: echo "add_subdirectory(test)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  gcc_5:
    docker:
      - image: enumack/buildcontainers:gcc-5
    steps:
      - checkout
      - run: echo "add_subdirectory(test/common)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/dual_number)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/interval)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/rkf45)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stopwatch)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      # - run: ./stream_lib_tests
      # - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_5_0:
    docker:
      - image: enumack/buildcontainers:clang-5.0
    steps:
      - checkout
      - run: echo "add_subdirectory(test)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_4_0:
    docker:
      - image: enumack/buildcontainers:clang-4.0
    steps:
      - checkout
      - run: echo "add_subdirectory(test)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_3_9:
    docker:
      - image: enumack/buildcontainers:clang-3.9
    steps:
      - checkout
      - run: echo "add_subdirectory(test/common)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/dual_number)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/interval)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stream)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/rkf45)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stopwatch)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      # - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_3_8:
    docker:
      - image: enumack/buildcontainers:clang-3.8
    steps:
      - checkout
      - run: echo "add_subdirectory(test/common)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/dual_number)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/interval)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stream)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/rkf45)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stopwatch)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      # - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests
  clang_3_7:
    docker:
      - image: enumack/buildcontainers:clang-3.7
    steps:
      - checkout
      - run: echo "add_subdirectory(test/common)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/dual_number)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/interval)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stream)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/rkf45)" >> ./CMakeLists.txt
      - run: echo "add_subdirectory(test/stopwatch)" >> ./CMakeLists.txt
      - run: cmake -DCMAKE_CXX_COMPILER=$CXX && make
      - run: ./common_lib_tests
      - run: ./dual_number_lib_tests
      - run: ./interval_lib_tests
      - run: ./stream_lib_tests
      # - run: ./func_util_lib_tests
      - run: ./rkf45_lib_tests
      - run: ./stopwatch_lib_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_5
      - gcc_6
      - gcc_7
      - clang_3_7
      - clang_3_8
      - clang_3_9
      - clang_4_0
      - clang_5_0