version: 2
jobs:
  gcc_7_1:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-7.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_7_2:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-7.2
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_1:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_2:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.2
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_3:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.3
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_6_4:
    working_directory: /Cranberries
    docker:
      - image: enumack/buildcontainers:gcc-6.4
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_1:
    docker:
      - image: enumack/buildcontainers:gcc-5.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_2:
    docker:
      - image: enumack/buildcontainers:gcc-5.2
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_3:
    docker:
      - image: enumack/buildcontainers:gcc-5.3
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_4:
    docker:
      - image: enumack/buildcontainers:gcc-5.4
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  gcc_5_5:
    docker:
      - image: enumack/buildcontainers:gcc-5.5
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4
  clang_5_0_0:
    docker:
      - image: enumack/buildcontainers:clang-5.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_4_0_0:
    docker:
      - image: enumack/buildcontainers:clang-4.0.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_4_0_1:
    docker:
      - image: enumack/buildcontainers:clang-4.0.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_9_0:
    docker:
      - image: enumack/buildcontainers:clang-3.9.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_9_1:
    docker:
      - image: enumack/buildcontainers:clang-3.9.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_8_0:
    docker:
      - image: enumack/buildcontainers:clang-3.8.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_8_1:
    docker:
      - image: enumack/buildcontainers:clang-3.8.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*func_util).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_7_0:
    docker:
      - image: enumack/buildcontainers:clang-3.7.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_7_1:
    docker:
      - image: enumack/buildcontainers:clang-3.7.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_6_0:
    docker:
      - image: enumack/buildcontainers:clang-3.6.0
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_6_1:
    docker:
      - image: enumack/buildcontainers:clang-3.6.1
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4
  clang_3_6_2:
    docker:
      - image: enumack/buildcontainers:clang-3.6.2
    steps:
      - checkout
      - run: $CXX -dumpversion
      - run: ls -F test | grep / | sed -E "s/(.*)\//add_subdirectory(test\/\1)/g" | grep -P "^(?!.*(stream|func_util)).*$" >> ./CMakeLists.txt
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-stdlib=libc++" && make && ctest --no-label-summary --parallel 4

workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      - gcc_5_1
      - gcc_5_2
      - gcc_5_3
      - gcc_5_4
      - gcc_5_5
      - gcc_6_1
      - gcc_6_2
      - gcc_6_3
      - gcc_6_4 
      - gcc_7_1
      - gcc_7_2
      # Clang
      - clang_3_6_0
      - clang_3_6_1
      - clang_3_6_2
      - clang_3_7_0
      - clang_3_7_1
      - clang_3_8_0
      - clang_3_8_0
      - clang_3_9_0
      - clang_3_9_1    
      - clang_4_0_0
      - clang_4_0_1
      - clang_5_0_0