#ifndef CRANBERRIES_STREAMS_CONCEPT_HPP
#define CRANBERRIES_STREAMS_CONCEPT_HPP

#define CRANBERRIES_ASSERT(...) \
static_assert(__VA_ARGS__,#__VA_ARGS__);

#endif // !CRANBERRIES_STREAMS_CONCEPT_HPP
