#ifndef CRANBERRIES_STREAMS_OPERATORS_HPP
#define CRANBERRIES_STREAMS_OPERATORS_HPP

#include "operators\AdjacentForEach.hpp"
#include "operators\All.hpp"
#include "operators\Any.hpp"
#include "operators\Concatenate.hpp"
#include "operators\Distinct.hpp"
#include "operators\Filter.hpp"
#include "operators\ForEach.hpp"
#include "operators\Invoker.hpp"
#include "operators\Take.hpp"
#include "operators\Map.hpp"
#include "operators\MapTo.hpp"
#include "operators\None.hpp"
#include "operators\PopBack.hpp"
#include "operators\PushBack.hpp"
#include "operators\Repetition.hpp"
#include "operators\Reverse.hpp"
#include "operators\Identity.hpp"
#include "operators\Drop.hpp"
#include "operators\Sort.hpp"
#include "operators\Printer.hpp"
#include "operators\Splitter.hpp"
#include "operators\DropWhile.hpp"
#include "operators\TakeWhile.hpp"
#include "operators\Unique.hpp"
#include "operators\Merge.hpp"
#include "operators\Peek.hpp"

#endif